[ 2025-06-06 16:47:21,916 ] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-06-06 16:47:21,933 ] 107 dagshub - INFO - Accessing as jatinydav557
[ 2025-06-06 16:47:22,822 ] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/jatinydav557/networksecurity "HTTP/1.1 200 OK"
[ 2025-06-06 16:47:23,642 ] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-06-06 16:47:23,655 ] 107 dagshub - INFO - Initialized MLflow to track repo "jatinydav557/networksecurity"
[ 2025-06-06 16:47:23,661 ] 107 dagshub - INFO - Repository jatinydav557/networksecurity initialized!
[ 2025-06-06 16:47:55,823 ] 34 root - INFO - Start data ingestion
[ 2025-06-06 16:48:03,055 ] 65 root - INFO - Performed train test split on the dataframe
[ 2025-06-06 16:48:03,055 ] 67 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2025-06-06 16:48:03,057 ] 75 root - INFO - Exporting train and test file path.
[ 2025-06-06 16:48:03,241 ] 84 root - INFO - Exported train and test file path.
[ 2025-06-06 16:48:03,243 ] 37 root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='Artifacts\\06_06_2025_16_47_16\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\06_06_2025_16_47_16\\data_ingestion\\ingested\\test.csv')
[ 2025-06-06 16:48:03,260 ] 49 root - INFO - Initiate the data Validation
[ 2025-06-06 16:48:03,510 ] 34 root - INFO - Required number of columns:2
[ 2025-06-06 16:48:03,511 ] 35 root - INFO - Data frame has columns:31
[ 2025-06-06 16:48:03,511 ] 34 root - INFO - Required number of columns:2
[ 2025-06-06 16:48:03,511 ] 35 root - INFO - Data frame has columns:31
[ 2025-06-06 16:48:03,966 ] 66 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2025-06-06 16:48:03,966 ] 68 root - INFO - Starting_data_transformation
[ 2025-06-06 16:48:04,069 ] 51 root - INFO - Entered get_data_trnasformer_object method of Trnasformation class
[ 2025-06-06 16:48:04,069 ] 56 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[ 2025-06-06 16:48:04,144 ] 49 root - INFO - Entered the save_object method of MainUtils class
[ 2025-06-06 16:48:04,157 ] 53 root - INFO - Exited the save_object method of MainUtils class
[ 2025-06-06 16:48:04,158 ] 49 root - INFO - Entered the save_object method of MainUtils class
[ 2025-06-06 16:48:04,173 ] 53 root - INFO - Exited the save_object method of MainUtils class
[ 2025-06-06 16:55:23,621 ] 49 root - INFO - Entered the save_object method of MainUtils class
[ 2025-06-06 16:55:23,629 ] 53 root - INFO - Exited the save_object method of MainUtils class
[ 2025-06-06 16:55:23,629 ] 49 root - INFO - Entered the save_object method of MainUtils class
[ 2025-06-06 16:55:23,700 ] 53 root - INFO - Exited the save_object method of MainUtils class
[ 2025-06-06 16:55:23,702 ] 142 root - INFO - Model trainer artifact: ModelTrainerArtifact(trained_model_file_path='Artifacts\\06_06_2025_16_47_16\\model_trainer\\trained_model\\model.pkl', train_metric_artifact=ClassificationMetricArtifact(f1_score=0.9910182662226259, precision_score=0.98653807514567, recall_score=0.9955393349553934), test_metric_artifact=ClassificationMetricArtifact(f1_score=0.9769510715729883, precision_score=0.967948717948718, recall_score=0.9861224489795918))
[ 2025-06-06 16:55:23,786 ] 1833 asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Jatin\AppData\Roaming\uv\python\cpython-3.12.10-windows-x86_64-none\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Jatin\AppData\Roaming\uv\python\cpython-3.12.10-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
